# Character images
# you had to use 'side' because you defined the images and characters with same names
image mc_sprite = "MC.png"
image mc_sprite phone ="MC/MCPhone.png"
image mc_sprite angry ="MC/MCAngry.png"
image mc_sprite depressed="MC/MCDepressed.png"
image mc_sprite intrigued ="MC/MCIntrigued.png"
image mc_sprite scared ="MC/MCScared.png"
image mc_sprite smoking ="MC/MCSmoke.png"
image pa_sprite = "PA/PANormal.png"
image pa_sprite angry = "PA/PAScared.png"
image pa_sprite depressed = "PA/PADepressed.png"
image pa_sprite intrigued = "PA/PAIntrigued.png"
image pa_sprite scared = "PA/PAScared.png"
image side doctor = "dr.png"
image side killer = "killer1.png"
image killer2_sprite = "killer2.png"
image asshole_cop1_sprite = "assholecop1.png"
image asshole_cop2_sprite = "assholecop2.png"
image villain_sprite = "villaingun.png"